/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ine5404.calculadora;

import ine5404.calculadora.modelo.Calculadora;

/**
 *
 * @author 17100508
 */
public class Moldura extends javax.swing.JFrame {

    /**
     * Creates new form Moldura
     */
    public Moldura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setText("First Number");
        jPanel1.add(jLabel1);
        jPanel1.add(jTextField1);

        jLabel2.setText("Second Number");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextField2);

        jLabel3.setText("Result");
        jPanel1.add(jLabel3);
        jPanel1.add(jLabel4);

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somar(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtrair(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("*");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicar(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setText("/");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividir(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("%");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percent(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear(evt);
            }
        });
        jPanel1.add(jButton6);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void somar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somar
        String numero1 = this.jTextField1.getText();
        String numero2 = this.jTextField2.getText();
        
        Double real1 = new Double(numero1);
        Double real2 = new Double(numero2);
        Calculadora calculadora = new Calculadora();
        
        Double resultado = calculadora.somar(real1, real2);

        this.jLabel4.setText(resultado.toString());
    }//GEN-LAST:event_somar

    private void subtrair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtrair
        String numero1 = this.jTextField1.getText();
        String numero2 = this.jTextField2.getText();
        
        Double real1 = new Double(numero1);
        Double real2 = new Double(numero2);
        
        Double resultado = real1 - real2;
        
        this.jLabel4.setText(resultado.toString());
    }//GEN-LAST:event_subtrair

    private void multiplicar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicar
        String numero1 = this.jTextField1.getText();
        String numero2 = this.jTextField2.getText();
        
        Double real1 = new Double(numero1);
        Double real2 = new Double(numero2);
        
        Double resultado = real1 * real2;
        
        this.jLabel4.setText(resultado.toString());
    }//GEN-LAST:event_multiplicar

    private void dividir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividir
        String numero1 = this.jTextField1.getText();
        String numero2 = this.jTextField2.getText();
        
        Double real1 = new Double(numero1);
        Double real2 = new Double(numero2);
        
        Calculadora calc = new Calculadora();
        
        Double resultado = calc.dividir(real1, real2);
        
        if(resultado != null){
            this.jLabel4.setText(resultado.toString());
        }
        else{
            this.jLabel4.setText("error");
        }
    }//GEN-LAST:event_dividir

    private void percent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percent
        String numero1 = this.jTextField1.getText();
        String numero2 = this.jTextField2.getText();
        
        Double real1 = new Double(numero1);
        Double real2 = new Double(numero2);
        
        if(real2 != 0){
            Double resultado = (real2 / real1)*100;
            this.jLabel4.setText(resultado.toString()+"%");
        }
        else{
            if(real1 != 0){
                this.jLabel4.setText("infinito");
            }
            else{
                this.jLabel4.setText("indeterminado");
            }
        }
    }//GEN-LAST:event_percent

    private void clear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear
        this.jTextField1.setText("");
        this.jTextField2.setText("");
        this.jLabel4.setText("");
    }//GEN-LAST:event_clear

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moldura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moldura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moldura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moldura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Moldura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
